<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  exclude-result-prefixes="sitemap image">

<xsl:output method="html" encoding="UTF-8" indent="yes"/>

<!-- ── Sitemap Index ─────────────────────────────────────── -->
<xsl:template match="/sitemap:sitemapindex">
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>XML Sitemap Index</title>
  <style><![CDATA[
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;background:#f8fafc;color:#1e293b;font-size:14px}
    header{background:#2563eb;color:#fff;padding:24px 32px;display:flex;align-items:center;gap:16px}
    header h1{font-size:22px;font-weight:700}
    header p{font-size:13px;opacity:.8;margin-top:4px}
    .badge{background:rgba(255,255,255,.2);border-radius:20px;padding:4px 12px;font-size:12px;font-weight:600;white-space:nowrap}
    main{max-width:960px;margin:32px auto;padding:0 24px}
    .meta{display:flex;gap:16px;margin-bottom:20px;flex-wrap:wrap}
    .meta-item{background:#fff;border:1px solid #e2e8f0;border-radius:8px;padding:12px 18px;flex:1;min-width:160px}
    .meta-item .label{font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:.5px}
    .meta-item .value{font-size:20px;font-weight:700;color:#2563eb;margin-top:4px}
    table{width:100%;border-collapse:collapse;background:#fff;border-radius:10px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.06)}
    thead{background:#2563eb;color:#fff}
    thead th{padding:12px 16px;text-align:left;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:.5px}
    tbody tr{border-bottom:1px solid #f1f5f9;transition:background .15s}
    tbody tr:hover{background:#f0f7ff}
    tbody tr:last-child{border-bottom:none}
    td{padding:12px 16px;vertical-align:middle}
    td a{color:#2563eb;text-decoration:none;font-weight:500}
    td a:hover{text-decoration:underline}
    .lastmod{color:#64748b;font-size:12px;white-space:nowrap}
    .type-badge{display:inline-block;background:#dbeafe;color:#1d4ed8;border-radius:4px;padding:2px 8px;font-size:11px;font-weight:600;margin-right:6px}
    footer{text-align:center;color:#94a3b8;font-size:12px;margin:32px 0 16px}
  ]]></style>
</head>
<body>
<header>
  <div>
    <h1>🗺 XML Sitemap Index</h1>
    <p>Generated by AumViso Plugin · For search engine crawlers</p>
  </div>
  <div class="badge"><xsl:value-of select="count(sitemap:sitemap)"/> Sub-Sitemaps</div>
</header>
<main>
  <div class="meta">
    <div class="meta-item">
      <div class="label">Sub-Sitemaps</div>
      <div class="value"><xsl:value-of select="count(sitemap:sitemap)"/></div>
    </div>
    <div class="meta-item">
      <div class="label">Generated By</div>
      <div class="value" style="font-size:14px;padding-top:6px;">AumViso Dynamic</div>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Sitemap URL</th>
        <th>Type</th>
        <th>Last Modified</th>
      </tr>
    </thead>
    <tbody>
      <xsl:for-each select="sitemap:sitemap">
        <tr>
          <td>
            <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
          </td>
          <td>
            <xsl:choose>
              <xsl:when test="contains(sitemap:loc,'post-sitemap')"><span class="type-badge">Posts</span></xsl:when>
              <xsl:when test="contains(sitemap:loc,'page-sitemap')"><span class="type-badge">Pages</span></xsl:when>
              <xsl:when test="contains(sitemap:loc,'image-sitemap')"><span class="type-badge">Images</span></xsl:when>
              <xsl:when test="contains(sitemap:loc,'category-sitemap')"><span class="type-badge">Categories</span></xsl:when>
              <xsl:otherwise><span class="type-badge">Other</span></xsl:otherwise>
            </xsl:choose>
          </td>
          <td class="lastmod">
            <xsl:value-of select="sitemap:lastmod"/>
          </td>
        </tr>
      </xsl:for-each>
    </tbody>
  </table>
</main>
<footer>AumViso Plugin · <a href="https://www.sitemaps.org" style="color:#94a3b8">Sitemaps Protocol</a></footer>
</body>
</html>
</xsl:template>

<!-- ── URL Sitemap ───────────────────────────────────────── -->
<xsl:template match="/sitemap:urlset">
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>XML Sitemap</title>
  <style><![CDATA[
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;background:#f8fafc;color:#1e293b;font-size:14px}
    header{background:#2563eb;color:#fff;padding:24px 32px;display:flex;align-items:center;gap:16px;flex-wrap:wrap}
    header h1{font-size:22px;font-weight:700}
    header p{font-size:13px;opacity:.8;margin-top:4px}
    .badge{background:rgba(255,255,255,.2);border-radius:20px;padding:4px 12px;font-size:12px;font-weight:600;white-space:nowrap;margin-left:auto}
    .back{color:rgba(255,255,255,.7);font-size:13px;text-decoration:none;display:flex;align-items:center;gap:4px}
    .back:hover{color:#fff}
    main{max-width:1100px;margin:32px auto;padding:0 24px}
    .meta{display:flex;gap:16px;margin-bottom:20px;flex-wrap:wrap}
    .meta-item{background:#fff;border:1px solid #e2e8f0;border-radius:8px;padding:12px 18px;flex:1;min-width:140px}
    .meta-item .label{font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:.5px}
    .meta-item .value{font-size:20px;font-weight:700;color:#2563eb;margin-top:4px}
    table{width:100%;border-collapse:collapse;background:#fff;border-radius:10px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.06)}
    thead{background:#2563eb;color:#fff}
    thead th{padding:12px 16px;text-align:left;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:.5px}
    tbody tr{border-bottom:1px solid #f1f5f9;transition:background .15s}
    tbody tr:hover{background:#f0f7ff}
    tbody tr:last-child{border-bottom:none}
    td{padding:10px 16px;vertical-align:middle}
    td a{color:#2563eb;text-decoration:none}
    td a:hover{text-decoration:underline}
    .small{color:#64748b;font-size:12px;white-space:nowrap}
    .priority{display:inline-block;min-width:36px;text-align:center;background:#dbeafe;color:#1d4ed8;border-radius:4px;padding:2px 6px;font-size:12px;font-weight:700}
    .priority.high{background:#dcfce7;color:#16a34a}
    .priority.med{background:#fef3c7;color:#d97706}
    .img-count{display:inline-block;background:#f1f5f9;color:#475569;border-radius:4px;padding:1px 6px;font-size:11px}
    footer{text-align:center;color:#94a3b8;font-size:12px;margin:32px 0 16px}
  ]]></style>
</head>
<body>
<header>
  <div style="flex:1">
    <a class="back" href="sitemap.xml">← Back to Index</a>
    <h1 style="margin-top:6px">🗺 XML Sitemap</h1>
    <p>Generated by AumViso Plugin</p>
  </div>
  <div class="badge"><xsl:value-of select="count(sitemap:url)"/> URLs</div>
</header>
<main>
  <div class="meta">
    <div class="meta-item">
      <div class="label">Total URLs</div>
      <div class="value"><xsl:value-of select="count(sitemap:url)"/></div>
    </div>
    <div class="meta-item">
      <div class="label">With Images</div>
      <div class="value"><xsl:value-of select="count(sitemap:url[image:image])"/></div>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>URL</th>
        <th>Last Modified</th>
        <th>Change Freq</th>
        <th>Priority</th>
        <th>Images</th>
      </tr>
    </thead>
    <tbody>
      <xsl:for-each select="sitemap:url">
        <tr>
          <td class="small"><xsl:value-of select="position()"/></td>
          <td><a href="{sitemap:loc}" target="_blank"><xsl:value-of select="sitemap:loc"/></a></td>
          <td class="small"><xsl:value-of select="sitemap:lastmod"/></td>
          <td class="small"><xsl:value-of select="sitemap:changefreq"/></td>
          <td>
            <xsl:variable name="p" select="sitemap:priority"/>
            <xsl:choose>
              <xsl:when test="$p >= 0.8"><span class="priority high"><xsl:value-of select="$p"/></span></xsl:when>
              <xsl:when test="$p >= 0.6"><span class="priority med"><xsl:value-of select="$p"/></span></xsl:when>
              <xsl:otherwise><span class="priority"><xsl:value-of select="$p"/></span></xsl:otherwise>
            </xsl:choose>
          </td>
          <td>
            <xsl:if test="image:image">
              <span class="img-count"><xsl:value-of select="count(image:image)"/> img</span>
            </xsl:if>
          </td>
        </tr>
      </xsl:for-each>
    </tbody>
  </table>
</main>
<footer>AumViso Plugin · <a href="https://www.sitemaps.org" style="color:#94a3b8">Sitemaps Protocol</a></footer>
</body>
</html>
</xsl:template>

</xsl:stylesheet>
